# Generated by Django 5.2.5 on 2025-09-05 11:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0014_service'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Service',
        ),
    ]
